Repository gd-edit/GDE, pull requests merged in 2019-07, with the labels that each got.

#99 Implement IDMigrationKeybindings
  GDEdit/GDE.App/Main/Containers/KeyBindingContainers/IDMigrationActionContainer.cs
  GDEdit/GDE.App/Main/Panels/Panel.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/IDMigrationStepList.cs
  GDEdit/GDE.App/Main/Screens/Edit/EditorScreen.cs
  GDEdit/GDE.App/Main/Screens/Edit/IDMigrationScreen.cs
Labels: Backend, Enhancement

#95 Sneak peek future-proofing v201905250312+3:00
  GDEdit/GDEdit/GDEdit.csproj
  GDEdit/GDEdit/Utilities/Enumerations/GeometryDash/ObjectParameter.cs
  GDEdit/GDEdit/Utilities/Information/GeometryDash/LevelObjectInformation.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/OrbPad.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Orbs/Orb.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Orbs/TriggerOrb.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Pads/Pad.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/CameraOffsetTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/MoveTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/RandomTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/StaticCameraTrigger.cs
Labels: Enhancement

#107 Add support for some forgotten properties
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/GeneralObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/PulsatingObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/RotatingObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/MoveTrigger.cs
Labels: Backend, Enhancement

#109 Database loading fixes
  GDEdit/GDEdit/Application/Database.cs
  GDEdit/GDEdit/Utilities/Functions/GeometryDash/Gamesave.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/PulseTrigger.cs
Labels: Backend, Performance, Resolves Issue

#111 General level loading fixes
  GDEdit/GDEdit/Utilities/Enumerations/GeometryDash/ObjectParameter.cs
  GDEdit/GDEdit/Utilities/Information/GeometryDash/LevelObjectInformation.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/Level.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/SongMetadata.cs
Labels: Backend, Performance, Resolves Issue

#106 Migrate GDEdit project to .NET Standard 2.0
  GDEdit/GDEdit/GDEdit.csproj
Labels: Code Quality

#115 Quick implementations
  GDEdit/GDE.App/Main/Containers/KeyBindingContainers/IDMigrationActionContainer.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/IDMigrationStepList.cs
  GDEdit/GDEdit/Application/Editor/Editor.cs
Labels: Backend, UX
