Repository gd-edit/GDE, pull requests merged in 2019-08, with the labels that each got.

#119 Run code cleanup v2
  GDEdit/GDE.App/Main/Colors/GDEColors.cs
  GDEdit/GDE.App/Main/Containers/KeyBindingContainers/FileDialogActionContainer.cs
  GDEdit/GDE.App/Main/Containers/KeyBindingContainers/GlobalActionContainer.cs
  GDEdit/GDE.App/Main/Containers/KeyBindingContainers/IDMigrationActionContainer.cs
  GDEdit/GDE.App/Main/Containers/ZoomableContainer.cs
  GDEdit/GDE.App/Main/GDEApp.cs
  GDEdit/GDE.App/Main/GDEAppBase.cs
  GDEdit/GDE.App/Main/Hitboxes/RectangleHitbox.cs
  GDEdit/GDE.App/Main/Levels/Grid.cs
  GDEdit/GDE.App/Main/Levels/Grid/GridLine.cs
  GDEdit/GDE.App/Main/Levels/Grid/HorizontalGridLine.cs
  GDEdit/GDE.App/Main/Levels/Grid/VerticalGridLine.cs
  GDEdit/GDE.App/Main/Levels/LevelPreview.cs
  GDEdit/GDE.App/Main/Overlays/OverlayPopup.cs
  GDEdit/GDE.App/Main/Panels/CloseButton.cs
  GDEdit/GDE.App/Main/Panels/PinButton.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/Camera.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/EditorTools.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/IDMigration/IDMigrationTabControl.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/IDMigration/IDMigrationTabItem.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/IDMigrationStepList.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/Menu/EditorMenuBar.cs
  GDEdit/GDE.App/Main/Screens/Edit/Components/ObjectAdditionPanel.cs
  GDEdit/GDE.App/Main/Screens/Edit/EditorScreen.cs
  GDEdit/GDE.App/Main/Screens/Edit/IDMigrationPanel.cs
  GDEdit/GDE.App/Main/Screens/Lords.cs
  GDEdit/GDE.App/Main/Screens/Menu/Components/LevelCard.cs
  GDEdit/GDE.App/Main/Screens/Menu/Components/LevelList.cs
  GDEdit/GDE.App/Main/Screens/Menu/Components/Toolbar.cs
  GDEdit/GDE.App/Main/Screens/Menu/MainScreen.cs
  GDEdit/GDE.App/Main/Toasts/ToastNotification.cs
  GDEdit/GDE.App/Main/Tools/RPC.cs
  GDEdit/GDE.App/Main/Tools/RavenLogger.cs
  GDEdit/GDE.App/Main/UI/BreadcrumbNavigation.cs
  GDEdit/GDE.App/Main/UI/Containers/KeyBindingActionContainer.cs
  GDEdit/GDE.App/Main/UI/FadeButton.cs
  GDEdit/GDE.App/Main/UI/FadeSearchContainer.cs
  GDEdit/GDE.App/Main/UI/FileDialogComponents/DirectoryItemContainer.cs
  GDEdit/GDE.App/Main/UI/FileDialogComponents/DrawableItem.cs
  GDEdit/GDE.App/Main/UI/FileDialogComponents/FileDialog.cs
  GDEdit/GDE.App/Main/UI/FileDialogComponents/OpenFileDialog.cs
  GDEdit/GDE.App/Main/UI/FileDialogComponents/SaveFileDialog.cs
  GDEdit/GDE.App/Main/UI/GDEBreadcrumbNavigation.cs
  GDEdit/GDE.App/Main/UI/GDEBreadcrumbNavigationTextBox.cs
  GDEdit/GDE.App/Main/UI/GDEMenu.cs
  GDEdit/GDE.App/Main/UI/GDEMenuItem.cs
  GDEdit/GDE.App/Main/UI/Tabs/LevelTab.cs
  GDEdit/GDE.App/Main/UI/Toolbar/ToolbarMenuItem.cs
  GDEdit/GDE.App/Program.cs
  GDEdit/GDE.App/Updater/SquirrelUpdateManager.cs
  GDEdit/GDE.Tests/GDETestBrowser.cs
  GDEdit/GDE.Tests/Program.cs
  GDEdit/GDE.Tests/Visual/TestSceneEditor/TestSceneCamera.cs
  GDEdit/GDE.Tests/Visual/TestSceneEditor/TestSceneIDMigration.cs
  GDEdit/GDE.Tests/Visual/TestSceneEditor/TestSceneIDMigrationStepCard.cs
  GDEdit/GDE.Tests/Visual/TestSceneLevels/TestSceneHitbox.cs
  GDEdit/GDE.Tests/Visual/TestSceneLevels/TestSceneIDMigrationBackend.cs
  GDEdit/GDE.Tests/Visual/TestSceneUserInterface/TestSceneFileDialog.cs
Labels: Code Quality

#120 File dialog improvements
  GDEdit/GDE.App/Main/UI/BreadcrumbNavigation.cs
  GDEdit/GDE.App/Main/UI/FileDialogComponents/DirectoryItemContainer.cs
  GDEdit/GDE.App/Main/UI/FileDialogComponents/DrawableItem.cs
  GDEdit/GDE.App/Main/UI/FileDialogComponents/FileDialog.cs
  GDEdit/GDE.App/Main/UI/GDEBreadcrumbNavigationTextBox.cs
  GDEdit/GDEdit/Utilities/Enumerations/ItemType.cs
  GDEdit/GDEdit/Utilities/Functions/Extensions/StringExtensions.cs
  GDEdit/GDEdit/Utilities/Functions/General/PathExpansionPack.cs
Labels: Frontend

#121 Add object parameter defaults
  GDEdit/GDEdit/Utilities/Attributes/ColorStringMappableAttribute.cs
  GDEdit/GDEdit/Utilities/Attributes/ObjectStringMappableAttribute.cs
  GDEdit/GDEdit/Utilities/Objects/General/Color.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/General/HSVDifference.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/GeneralObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasColor.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasCopiedColorID.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasDuration.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasEasing.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasPrimaryBlockID.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasPrimaryItemID.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasSecondaryBlockID.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasSecondaryGroupID.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasTargetColorID.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasTargetGroupID.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Interfaces/IHasTargetItemID.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/CollisionBlock.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/CountTextObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/CustomParticleObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/IHasCheckedProperty.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/OrbPad.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Orbs/Orb.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Orbs/TriggerOrb.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/PickupItem.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Portals/GamemodePortals/BallPortal.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Portals/GamemodePortals/CheckableGamemodePortal.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Portals/GamemodePortals/ShipPortal.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Portals/GamemodePortals/SpiderPortal.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Portals/GamemodePortals/UFOPortal.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Portals/GamemodePortals/WavePortal.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Portals/SpeedPortals/SpeedPortal.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/PulsatingObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/RotatingObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/TextObject.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/AlphaTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/AnimateTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/CameraOffsetTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/CollisionTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/CountTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/EndTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/FollowPlayerYTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/FollowTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/InstantCountTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/MoveTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/OnDeathTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/PickupTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/PulseTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/RandomTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ReverseTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/RotateTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ScaleTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ShakeTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/SpawnTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/StaticCameraTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/StopTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ToggleTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/TouchTrigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Trigger.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ZoomTrigger.cs
Labels: Backend

#123 Speed constants
  GDEdit/GDEdit/Utilities/Information/GeometryDash/Speeds.cs
Labels: Backend
