Repository gd-edit/GDE, pull requests merged in 2019-03, with the labels that each got.

#63 Menu revamp
  GDEdit/GDE.App/GDE.App.csproj
  GDEdit/GDE.App/Main/Containers/GlobalActionContainer.cs
  GDEdit/GDE.App/Main/Containers/ZoomableContainer.cs
  GDEdit/GDE.App/Main/GDEApp.cs
  GDEdit/GDE.App/Main/GDEAppBase.cs
  GDEdit/GDE.App/Main/Levels/Grid.cs
  GDEdit/GDE.App/Main/Levels/LevelPreview.cs
  GDEdit/GDE.App/Main/Objects/ObjectBase.cs
  GDEdit/GDE.App/Main/Overlays/OverlayPopup.cs
  GDEdit/GDE.App/Main/Panels/Panel.cs
  GDEdit/GDE.App/Main/Screens/Edit/Editor.cs
  GDEdit/GDE.App/Main/Screens/LevelCreation.cs
  GDEdit/GDE.App/Main/Screens/Lords.cs
  GDEdit/GDE.App/Main/Screens/MainContainer.cs
  GDEdit/GDE.App/Main/Screens/MainScreen.cs
  GDEdit/GDE.App/Main/Screens/Menu/Components/LevelCard.cs
  GDEdit/GDE.App/Main/Screens/Menu/Components/Toolbar.cs
  GDEdit/GDE.App/Main/Screens/Menu/MainScreen.cs
  GDEdit/GDE.Resources/GDE.Resources.csproj
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_01_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_02_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_03_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_04_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_05_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_06_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_07_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_08_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_09_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_10_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_11_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_12_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_13_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_14_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_15_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_16_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_17_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_18_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_19_001-uhd.png
  GDEdit/GDE.Resources/Textures/Backgrounds/game_bg_20_001-uhd.png
  GDEdit/GDE.Resources/Textures/Objects/103.png
  GDEdit/GDE.Resources/Textures/Objects/36.png
  GDEdit/GDE.Resources/Textures/Objects/39.png
  GDEdit/GDE.Resources/Textures/Objects/spike_02_001.png
  GDEdit/GDE.Resources/Textures/Objects/spike_03_001.png
  GDEdit/GDE.Resources/Textures/Untitled.png
  GDEdit/GDE.Tests/Visual/TestCaseEditor.cs
  GDEdit/GDE.Tests/Visual/TestCaseLevelCard.cs
  GDEdit/GDE.Tests/Visual/TestCaseLevelOverview.cs
  GDEdit/GDE.Tests/Visual/TestCaseObject.cs
  GDEdit/GDE.Tests/Visual/TestCaseOverlayPopup.cs
  GDEdit/GDE.Tests/Visual/TestCaseTheme.cs
  GDEdit/GDEdit/Application/Database.cs
  GDEdit/GDEdit/GDEdit.csproj
Labels: Frontend

#72 XML function refactoring
  GDEdit/GDEdit/GDEdit.csproj
  GDEdit/GDEdit/Utilities/Objects/General/XMLAnalyzer.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/Level.cs
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/SongMetadata.cs
Labels: Backend, Closes issue, Enhancement

#73 Fix editor test case
  GDEdit/GDE.Tests/Visual/TestCaseEditor.cs
Labels: Closes issue

#78 Database improvements
  GDEdit/GDEdit/Utilities/Objects/GeometryDash/Level.cs
Labels: Backend, Enhancement, WIP
